version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres16_Copy
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: credit_approval
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - credit_network

  web:
    build: .
    container_name: django_app
    volumes:
      - ./Backend:/app/Backend
      - ./Scripts:/app/Scripts
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - credit_network


networks:
  credit_network:

volumes:
  postgres_data:
