# Generated by Django 5.2.6 on 2025-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('monthly_income', models.BigIntegerField()),
                ('approved_limit', models.BigIntegerField()),
                ('phone_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
