# Generated by Django 5.2.6 on 2025-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_income',
            field=models.IntegerField(),
        ),
    ]
