# Generated by Django 5.2.6 on 2025-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_approved_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_income',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
